### ISSUE TITLE
Deploy fails on Linux

### ISSUE THREAD

**Issue by mmacfadden** [zhevron/gulp-deploy-git#1]
We are successfully using this plugin on Windows and Mac OSX.  However it fails to run on Linux.  The error is shown below.

```
[16:20:09] 'snapshot' errored after 73 ms
[16:20:09] Error in plugin 'gulp-deploy-git'
Message:
    Branch null is not configured to deploy
[16:20:09] git rev-parse: master
[16:20:09] Current branch: master
```

The error is happening because of the differences in how the child_process.spawn seems to be working on Linux vs the other operating systems.  On Windows and OSX.  The 'data' event is happening before the exit event.  This means that the output of the git commands is being received before the process notifies gulp that it exited.  The plugin us the 'data' event to scrape info from the git CLI.  The exit event is being used to trigger the rest of the process, which assumes the data has already been gotten from the CLI.

In Linux the 'exit' event is firing first.  You can see in the above output that the error message says "Branch null is not configured to deploy".  This is because the branch variable is not set yet.  This code is inside the callback for exit.  Then the last two lines show that the 'data' event has fired.  The correct data is retrieved, but it is to late.

The 'close' event from the span method waits until the io streams from the child process are closed and all data is flushed.  The 'close' event is used elsewhere in the code already.  I tested changing the code to use 'close' and this resolved the issue.

I will submit a pull request for review.

**Comment by zhevron** [comment]
Merged #2
