### ISSUE TITLE
Deploy fails with empty commit message

### ISSUE THREAD

**Issue by pfista** [zhevron/gulp-deploy-git#3]
I'm not sure how to prevent this error from occurring. Git log picks up the latest local commit, but it isn't being applied to the generated deploy folder.

```
[10:51:20] git log: f5f096d adding blog link to footer
[10:51:20] Committing changes to deployment repository
[10:51:20] git commit: Aborting commit due to empty commit message.
```

My gulpfile is configured as follows:

```
gulp.task('deploy', function() {
  return gulp.src('src/**/*')
    .pipe(deploy({
      repository: '   ...   ',
      verbose: true,
      prefix: 'src',
      debug: true
      }));
    });
```

**Comment by zhevron** [comment]
That's what I get for not actually testing that functionality. I have to use a custom message to deploy mine due to limitations forced on me by the CI system.

I did, however, locate the bug causing this. I'll see if I can get it fixed tonight!

**Comment by pfista** [comment]
Awesome. Thanks for the quick turnaround on this!
