### ISSUE TITLE
Always Tries to Push to Master Branch

### ISSUE THREAD

**Issue by masahs** [zhevron/gulp-deploy-git#7]
I have this task to push my deploy files to git:

```
var deploy = require('gulp-deploy-git');

gulp.task('gitdeploy', function() {
  return gulp.src(path.join(options.paths.iva_project_parent_prefix, options.paths.iva_path_prefix, '**/*'),{read: false})
    .pipe(deploy({
      repository: 'git@gitlab.xxx.xx.xx:xx/xx.git',
      message: "deploy",
      branches: ['geneva'],
      verbose: true,
      debug: true
    }))
});
```

and it process the files  fine but the push fails at the end

```
[15:46:50] git rev-parse: master
[15:37:58] Current branch: master
[15:37:58] Branch master not configured to deploy, skipping
```

So that would be a correct statement if I wanted to try and write to the "master" branch as it is locked, but I am trying to write to another branch that is not. In this case the branch is "geneeva" and it does not have deploy restrictions.

Any reason it does not recognize that I want to write to another branch?

**Comment by zhevron** [comment]
That message appears when you're trying to run `gulp gitdeploy` with the `master` branch checked out? Or do you have the `geneva` branch checked out?

If you just want to write to the remote branch, say you want your local `master` branch pushed to `geneva` on the deploy host, the correct settings would be more like:

```
.pipe(deploy({
    repository: 'git@gitlab.xxx.xx.xx:xx/xx.git',
    branches: ['master'],
    remoteBranch: 'geneva'
}))
```

**Comment by masahs** [comment]
I currently have the "geneeva" branch checked out. Your suggestion for setting branches to master and remoteBranch to "geneeva" worked. I had just looked at your documentation before you replied and was going to to try to work with the remote branch but I initially got the syntax wrong. Thanks for your quick reply and clearing this up. Huge help!

**Comment by zhevron** [comment]
No worries! Glad you got it sorted out.
