### ISSUE TITLE
Send just content of dist folder

### ISSUE THREAD

**Issue by hiwllc** [zhevron/gulp-deploy-git#8]
Hi, I'm trying to make deploy from local branch `master` to remote branch `master`, before this I run a task to make a `build` of my application and generate assets on folder `dist` then I run the task for deploy, but, for some reason I can't send only content from `dist` folder, my task look like this:

``` js
gulp.task('deploy', ['build'], () => {
  return gulp.src('dist/**', {read: false})
    .pipe(deploy({
      repository: 'https://github.com/uselessdev/uselessdev.github.io.git',
      verbose: true,
      debug: true
    }))
})
```

**Comment by zhevron** [comment]
Seems you're using an incorrect glob. The `**` glob will only match folders AFAIK. Try this:

```js
gulp.task('deploy', ['build'], () => {
  return gulp.src('dist/*', {read: false})
    .pipe(deploy({
      repository: 'https://github.com/uselessdev/uselessdev.github.io.git',
      verbose: true,
      debug: true
    }))
})
```

**Comment by hiwllc** [comment]
Thanks for reply :smile: 

I've tested using just `dist/*`, but no success, it still sends the whole dist folder [as you can see here](https://github.com/uselessdev/uselessdev.github.io), and I just wanna send the content of that folder.

**Comment by zhevron** [comment]
Oh, you mean like _that_. Makes more sense. A prefix strip should take care of that:

```js
gulp.task('deploy', ['build'], () => {
  return gulp.src('dist/**/*', {read: false})
    .pipe(deploy({
      repository: 'https://github.com/uselessdev/uselessdev.github.io.git',
      prefix: 'dist',
      verbose: true,
      debug: true
    }))
})
```

**Comment by hiwllc** [comment]
wow, it work! thanks man :+1:
